"""
chat.py

Per-video chat: answer questions about a processed video using its
chunk summaries as context. Scoped to a single job_id - no cross-video
indexing (that could be a future step, not needed now).

Calls the same VLM already pulled for analysis, but in text-only mode
(no images) - the summaries already contain the grounded visual/dialogue
detail, so re-sending frames per chat question would be slow and adds
no value.
"""

import httpx

from jobs import JobState

OLLAMA_URL = "http://localhost:11434/api/chat"
CHAT_MODEL = "qwen2.5vl:7b"

SYSTEM_PROMPT = (
    "You are answering questions about a video, based only on the "
    "segment-by-segment summaries provided below. These summaries were "
    "generated by analyzing the video's frames and transcript in order. "
    "Answer using only information present in these summaries. If the "
    "answer isn't in the summaries, say so explicitly rather than "
    "guessing or inventing details."
)


def _build_context(state: JobState) -> str:
    if state.final_summary:
        return f"Full video summary:\n{state.final_summary}"
    # Job still running or no final summary yet - fall back to raw
    # per-chunk notes collected so far, so chat still works mid-run.
    chunk_lines = "\n".join(f"Chunk {c['chunk']}: {c['summary']}" for c in state.chunks)
    return f"Segment-by-segment notes so far (video still processing):\n{chunk_lines}"


async def answer_question(state: JobState, question: str) -> str:
    context = _build_context(state)
    user_content = (
        f"{context}\n\n"
        f"Question: {question}\n\n"
        "Answer concisely and specifically, referencing details from "
        "the summaries above where relevant."
    )

    payload = {
        "model": CHAT_MODEL,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_content},
        ],
        "stream": False,
    }

    async with httpx.AsyncClient(timeout=120.0) as client:
        resp = await client.post(OLLAMA_URL, json=payload)
        resp.raise_for_status()
        data = resp.json()

    return data.get("message", {}).get("content", "")
